# Generated by Django 4.1.3 on 2022-12-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Iron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название утюга')),
                ('type', models.CharField(max_length=200, verbose_name='Вид утюга')),
                ('sole', models.CharField(max_length=200, verbose_name='Материал подошвы')),
                ('volume', models.IntegerField(verbose_name='Обьем резервуара для воды')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('more', models.TextField(blank=True, null=True, verbose_name='В комплекте')),
                ('image', models.ImageField(null=True, upload_to='img/products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('stock', models.IntegerField(default=1, verbose_name='Имеется в наличии')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Утюг',
                'verbose_name_plural': 'Утюги',
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название велосипеда')),
                ('kind', models.CharField(max_length=200, verbose_name='Класс велосипеда')),
                ('wheels', models.IntegerField(verbose_name='Диаметр колес')),
                ('growth', models.CharField(max_length=200, verbose_name='Рост')),
                ('front_brake_type', models.CharField(max_length=200, null=True, verbose_name='Тип переднего тормоза')),
                ('rear_brake_type', models.CharField(max_length=200, null=True, verbose_name='Тип заднего тормоза')),
                ('material', models.CharField(max_length=100, verbose_name='Материал рамы')),
                ('image', models.ImageField(null=True, upload_to='img/products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('stock', models.IntegerField(default=1, verbose_name='Имеется в наличии')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
    ]
