# Generated by Django 4.1.3 on 2022-12-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Полная стоимость')),
                ('in_order', models.BooleanField(default=False)),
                ('bicycles', models.ManyToManyField(blank=True, related_name='related_cart', to='products.bicycle', verbose_name='Велосипеды для корзины')),
                ('irons', models.ManyToManyField(blank=True, related_name='related_cart', to='products.iron', verbose_name='Утюги для корзины')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
