# Generated by Django 4.1.3 on 2022-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Полная стоимость'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во товара'),
        ),
    ]
